name = "shenzhen"
version = "0.1.0"
defaultTargets = ["shenzhen"]
leanOptions = {weak.lang.lemmaCmd=true}

[[lean_lib]]
name = "Shenzhen"

[[lean_exe]]
name = "shenzhen"
root = "Main"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"
